In [18]:
import os 
import json
import pandas as pd
import numpy as np

In [19]:
notebook_path = os.getcwd()
notebook_path

'C:\\Users\\VEDANG BARMAN\\Desktop\\Regulatory Compliance Agent\\sandbox\\jupyter'

In [20]:
in_dir_data = os.path.abspath(os.path.join(notebook_path,"..","..","Data","notification_historical","updated_notifications.jsonl"))

In [21]:
data = pd.read_json(in_dir_data,lines = True)

In [22]:
data.head()

,id,title,category,url,text
0,12931,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/373\nDOR.FIN.REC.No.292/03-10-...
1,12932,Reserve Bank of India (Non-Operative Financial...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DoR/2025-26/372\nDoR.LIC.REC.No.291/16.13....
2,12933,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/371\nDOR.FIN.REC.290/ 03-10-03...
3,12934,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/370\nDOR.FIN.REC.No.289/03.10....
4,12935,Reserve Bank of India (Mortgage Guarantee Comp...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/369\nDOR.FIN.REC.No.288/23-11-...

In [23]:
data.isnull().sum()

id          0
title       0
category    0
url         0
text        0
dtype: int64

In [24]:
data["doc_type"] = 'circular'
data.head()

,id,title,category,url,text,doc_type
0,12931,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/373\nDOR.FIN.REC.No.292/03-10-...,circular
1,12932,Reserve Bank of India (Non-Operative Financial...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DoR/2025-26/372\nDoR.LIC.REC.No.291/16.13....,circular
2,12933,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/371\nDOR.FIN.REC.290/ 03-10-03...,circular
3,12934,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/370\nDOR.FIN.REC.No.289/03.10....,circular
4,12935,Reserve Bank of India (Mortgage Guarantee Comp...,NBFC,https://rbi.org.in/scripts/NotificationUser.as...,RBI/DOR/2025-26/369\nDOR.FIN.REC.No.288/23-11-...,circular

In [25]:
in_dir_master_directory = os.path.abspath(os.path.join(notebook_path,"..","..","Data","master_directory","master_directory.jsonl"))

In [26]:
data_directory = pd.read_json(in_dir_master_directory,lines= True)

In [27]:
data_directory.head()

,id,title,category,url,text
0,12931,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DOR/2025-26/373\nDOR.FIN.REC.No.292/03-10-...
1,12932,Reserve Bank of India (Non-Operative Financial...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DoR/2025-26/372\nDoR.LIC.REC.No.291/16.13....
2,12933,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DOR/2025-26/371\nDOR.FIN.REC.290/ 03-10-03...
3,12934,Reserve Bank of India (Non-Banking Financial C...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DOR/2025-26/370\nDOR.FIN.REC.No.289/03.10....
4,12935,Reserve Bank of India (Mortgage Guarantee Comp...,NBFC,https://rbi.org.in/scripts/BS_ViewMasDirection...,RBI/DOR/2025-26/369\nDOR.FIN.REC.No.288/23-11-...

In [36]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    print(data_directory['title'])

0                                                     Reserve Bank of India (Non-Banking Financial Companies – Miscellaneous) Directions, 2025 (Updated as on February 26, 2026)
1                                                           Reserve Bank of India (Non-Operative Financial Holding Companies) Directions, 2025 (Updated as on December 05, 2025)
2                                                                            Reserve Bank of India (Non-Banking Financial Companies – Microfinance Institution) Directions, 2025
3                                                                       Reserve Bank of India (Non-Banking Financial Companies – Peer to Peer Lending Platform) Directions, 2025
4                                                                           Reserve Bank of India (Mortgage Guarantee Companies) Directions, 2025 (Updated as on March 10, 2026)
5                                                                                  Reserve Bank of India (Non-Banking Financial Companies - Account Aggregator) Directions, 2025
6                                                                              Reserve Bank of India (Core Investment Companies) Directions, 2025 (Updated as on March 10, 2026)
7                                                                             Reserve Bank of India (Standalone Primary Dealers) Directions, 2025 (Updated as on March 10, 2026)
8                                                                              Reserve Bank of India (Housing Finance Companies) Directions, 2025 (Updated as on April 15, 2026)
9                                              Reserve Bank of India (Non-Banking Financial Companies – Climate Finance and Management of Climate Change Risks) Directions, 2025
10                                                                      Reserve Bank of India (Non-Banking Financial Companies – Managing Risks in Outsourcing) Directions, 2025
11                                          Reserve Bank of India (Non-Banking Financial Companies – Responsible Business Conduct) Directions, 2025 (Updated as on July 1, 2026)
12                                               Reserve Bank of India (Non-Banking Financial Companies – Know Your Customer) Directions, 2025 (Updated as on December 29, 2025)
13                         Reserve Bank of India (Non-Banking Financial Companies – Prudential Norms on Declaration of Dividends) Directions, 2025 (Updated as on July 01, 2026)
14                   Reserve Bank of India (Non-Banking Financial Companies – Financial Statements: Presentation and Disclosures) Directions, 2025 (Updated as on July 01, 2026)
15                  Reserve Bank of India (Non-Banking Financial Companies – Treatment of Wilful Defaulters and Large Defaulters) Directions, 2025 (Updated as on July 01, 2026)
16                                         Reserve Bank of India (Non-Banking Financial Companies – Resolution of Stressed Assets) Directions, 2025 (updated as on July 1, 2026)
17            Reserve Bank of India (Non-Banking Financial Companies – Income Recognition, Asset Classification and Provisioning) Directions, 2025 (updated as on July 01, 2026)
18                                           Reserve Bank of India (Non-Banking Financial Companies – Asset Liability Management) Directions, 2025 (Updated as on July 01, 2026)
19      Reserve Bank of India (Non-Banking Financial Companies – Classification, Valuation and Operation of Investment Portfolio) Directions, 2025 (Updated as on July 01, 2026)
20                                          Reserve Bank of India (Non-Banking Financial Companies – Securitisation Transactions) Directions, 2025 (Updated as on July 01, 2026)
21                             Reserve Bank of India (Non-Banking Financial Companies - Transfer and Distribution of Credit Risk) Directions, 2025 (Updated as on July 01, 2026)
22                                      Reserve Bank of India (Non-Banking Financial Companies - Concentration Risk Management) Directions, 2025 (Updated as on August 25, 2026)
23                                               Reserve Bank of India (Non-Banking Financial Companies – Credit Risk Management) Directions, 2025 (Updated as on July 01, 2026)
24                                         Reserve Bank of India (Non-Banking Financial Companies – Credit Information Reporting) Directions, 2025 (Updated as on July 01, 2026)
25                                                                 Reserve Bank of India (Non-Banking Financial Companies – Credit Cards: Issuance and Conduct) Directions, 2025
26                                                    Reserve Bank of India (Non-Banking Financial Companies – Credit Facilities) Directions, 2025 (updated as on July 15, 2026)
27                                       Reserve Bank of India (Non-Banking Financial Companies – Acceptance of Public Deposits) Directions, 2025 (Updated as on April 15, 2026)
28                                 Reserve Bank of India (Non-Banking Financial Companies – Prudential Norms on Capital Adequacy) Directions, 2025 (Updated as on July 01, 2026)
29                                                           Reserve Bank of India (Non-Banking Financial Companies – Governance) Directions, 2025 (Updated as on June 24, 2026)
30                                    Reserve Bank of India (Non-Banking Financial Companies – Undertaking of Financial Services) Directions, 2025 (Updated as on July 01, 2026)
31                                                Reserve Bank of India (Non-Banking Financial Companies – Branch Authorisation) Directions, 2025 (Updated as on April 15, 2026)
32                                                                             Reserve Bank of India (Non-Banking Financial Companies – Voluntary Amalgamation) Directions, 2025
33                                                             Reserve Bank of India (Non-Banking Financial Companies – Acquisition of Shareholding or Control) Directions, 2025
34    Reserve Bank of India (Non-Banking Financial Companies – Registration, Exemptions and Framework for Scale Based Regulation) Directions, 2025 (Updated as on July 01, 2026)
35                                                                                   Reserve Bank of India (Non-Banking Financial Companies - Auditor’s Report) Directions, 2026
36                                                                          Reserve Bank of India (Non-Banking Financial Companies – Miscellaneous) Supervisory Directions, 2026
37                                                                                Reserve Bank of India (Non-Banking Financial Companies - Supervisory Returns) Directions, 2026
38                                                                                    Reserve Bank of India (Non-Banking Financial Companies - Statutory Audit) Directions, 2026
39                                                                            Reserve Bank of India (Non-Banking Financial Companies - Internal Audit Function) Directions, 2026
40                                                                              Reserve Bank of India (Non-Banking Financial Companies – Fraud Risk Management) Directions, 2026
41                                                                  Reserve Bank of India (Non-Banking Financial Companies – Digital Payment Security Controls) Directions, 2026
42                                                                  Reserve Bank of India (Non-Banking Financial Companies – Digital Payment Security Controls) Directions, 2026
43                                Reserve Bank of India (Non-Banking Financial Companies – Cybersecurity, Technology: Risk, Resilience and Assurance Framework) Directions, 2026
44                                                                                Reserve Bank of India (Non-Banking Financial Companies - Compliance Function) Directions, 2026
Name: title, dtype: str

In [35]:
with pd.option_context('display.max_colwidth', None):
    print(data_directory['text'].head(1))

0    RBI/DOR/2025-26/373\nDOR.FIN.REC.No.292/03-10-119/2025-26\nNovember 28, 2025\nPrevious Versions\nReserve Bank of India (Non-Banking Financial Companies – Miscellaneous) Directions, 2025 (Updated as on February 26, 2026)\nTable of Contents\nChapter-I - Preliminary\nChapter-II – Miscellaneous instructions applicable to NBFCs in Base Layer\nChapter-III – Miscellaneous Instructions applicable to NBFCs in Middle Layer\nChapter-IV – Specific directions applicable to NBFC-Factors and NBFC-ICCs registered under the Factor Regulation Act, 2011\nChapter-V – Specific directions applicable to Infrastructure Debt Funds – Non-Banking Financial Company (IDF-NBFCs)\nChapter-VI – Repeal and Other Provisions\nIn exercise of the powers conferred under sections 45JA, 45K, 45L and 45M of the Reserve Bank of India Act, 1934 (Act 2 of 1934), section 3 read with section 31A and section 6 of the Factoring Regulation Act, 2011 (Act 12 of 2012), and Sections 30, 30A, 32 and 33 of the National Housing Bank Act, 1987 (Act 53 of 1987), and of all powers enabling it in this behalf, the Reserve Bank having considered it necessary in the public interest, and being satisfied that, for the purpose of enabling the Reserve Bank to regulate the financial system to the advantage of the country and to prevent the affairs of any Non-Banking Financial Company (NBFC) from being conducted in a manner detrimental to the interest of investors and depositors or in any manner prejudicial to the interest of such NBFCs, hereby issues the Directions hereinafter specified.\nChapter-I Preliminary\nA. Short Title and Commencement\n1. These Directions shall be called the Reserve Bank of India (Non-Banking Financial Companies – Miscellaneous) Directions, 2025.\n2. These Directions shall come into effect on the day they are placed on the website of the Reserve Bank.\nB. Applicability\n3. The applicability of these Directions is as follows\n(1) These Directions shall be applicable to the following Non-Banking Financial Companies (hereinafter collectively referred to as ‘NBFCs’ and individually as ‘an NBFC’), subject to layer-wise applicability, unless stated otherwise:\n(i) NBFCs classified under the Base Layer (NBFC-BL) shall be required to comply with the provisions of Chapter II and NBFCs in the Middle Layer (NBFC-ML) or above layers shall comply with Chapters II and III, unless stated otherwise.\n(ii) The provisions given in Chapter II and III shall apply to the following, subject to layer-wise applicability, unless specified otherwise:\n(a) NBFC-D registered with the RBI under the provisions of the RBI Act, 1934;\n(b) NBFC-ICC registered with the RBI under the provisions of the RBI Act, 1934;\n(c) NBFC-Factor registered with the RBI under the provisions of the Factoring Regulation Act, 2011;\n(d) NBFC-MFI registered with the RBI under the provisions of the RBI Act, 1934;\n(e) NBFC-IFC registered with the RBI under the provisions of the RBI Act, 1934;\n(f) IDF-NBFC registered with the RBI under the provisions of the RBI Act, 1934.\n(iii) The provisions contained in paragraphs 6 to 22 and paragraphs 24 to 27, shall be applicable to HFC registered with the RBI under the provisions of the NHB Act, 1987.\n(iv) The provisions contained in paragraphs 6, 7, 14, 15, 25 and 26 shall be applicable to MGC registered with RBI under the scheme of Registration of Mortgage Guarantee Companies.\n(v) The provisions contained in paragraphs 6, 7, 8, 14, 15, 25 and 26 shall be applicable to SPD registered with the RBI as NBFC under the provisions of the RBI Act, 1934.\n(vi) The provisions contained in paragraphs 6, 7, 14, 15, 25 and 26 shall be applicable to NBFC-P2P registered with the RBI under the provisions of the RBI Act, 1934.\n(vii) The provisions contained in paragraphs 6, 7, 25 and 26 shall be applicable to NBFC-AA registered with the RBI under the provisions of the RBI Act, 1934.\n(viii) The provisions contained in paragraphs 6, 7, 9 to 20, and 25 to 27, shall be applicable to CIC registered with the RBI under the provisions of the RBI Act, 1934.\n(ix) The provisions contained in Chapter IV shall be applicable to NBFC-Factor registered with the RBI under the provisions of the Factoring Regulation Act, 2011 and NBFC-ICC registered with the RBI under the provisions of the Factoring Regulation Act, 2011.\n(x) The provisions contained in Chapter V shall be applicable to IDF-NBFC registered with the RBI under the provisions of the RBI Act, 1934.\n(2) These Directions are not applicable to the following:\n(i) NOFHC registered with the RBI as NBFC under the provisions of the RBI Act, 1934.\nNote: The applicability under these Directions is in line with the regulatory structure for NBFCs as set out in\nReserve Bank of India (Non-Banking Financial Companies – Registration, Exemptions and Framework for Scale Based Regulation) Directions, 2025\n.\nC. Definitions\n4. In this Chapter, unless the context otherwise requires, the terms herein shall bear the meanings assigned to them and as defined in the\nReserve Bank of India (Non-Banking Financial Companies – Registration, Exemptions and Framework for Scale Based Regulation) Directions, 2025\n.\n5. The words or expressions used in these Directions but not defined herein and defined in the Reserve Bank of India Act, 1934 (Act 2 of 1934), or the Banking Regulation Act, 1949 (Act 10 of 1949) shall have the same meaning as assigned to them under the said Acts. Any other words or expressions not defined in the said Acts shall have the same meaning as assigned to them in the Companies Act, 1956 or Companies Act, 2013.\nChapter-II Miscellaneous instructions applicable to NBFCs in Base Layer\nA. Information with respect to change of address, auditors, etc., to be submitted\n6. NBFCs shall communicate, not later than one month from the occurrence of any change in the complete postal address, telephone number/s and fax number/s of the registered/ corporate office to the Regional Office of the Department of Supervision of the Reserve Bank under whose jurisdiction it is registered and to the Department of Regulation, Central Office, Reserve Bank.\n7. NBFCs shall communicate, not later than one month from the occurrence of any change in:\n(1) the names and residential addresses of the directors of the company;\n(2) the names and the official designations of its principal officers;\n(3) the names and office address of the auditors of the company; and\n(4) the specimen signatures of the officers authorised to sign on behalf of the company.\nto the Regional Office of the Department of Supervision of the Reserve Bank under whose jurisdiction it is registered.\nB. Appointment of Statutory Central Auditors/Statutory Auditors\n8. NBFCs shall adhere to the instructions contained in circular titled ‘\nGuidelines for Appointment of Statutory Central Auditors (SCAs)/ Statutory Auditors (SAs) of Commercial Banks (excluding RRBs), UCBs and NBFCs (including HFCs)’ dated April 27, 2021\n, as amended from time to time. However, non-deposit taking NBFCs with asset size below ₹1,000 crore have the option to continue with their extant procedure.\nC. Raising Money through Private Placement by NBFCs\n9. NBFCs shall follow the guidelines on private placement of Non-Convertible Debentures (NCDs) given as under. The provisions of Companies Act, 2013 and Rules framed thereunder shall be applicable wherever not contradictory.\nC.1 Guidelines on Private Placement of NCDs (maturity more than one year) by NBFCs\n10. NBFCs shall put in place a Board approved policy for resource planning which, inter-alia, shall cover the planning horizon and the periodicity of private placement.\n11. The issues shall be governed by the following instructions:\n(1) The minimum subscription per investor shall be ₹20,000 (Rupees Twenty thousand);\n(2) The issuance of private placement of NCDs shall be in two separate categories, those with a maximum subscription of less than ₹1 crore and those with a minimum subscription of ₹1 crore and above per investor;\n(3) There shall be a limit of 200 subscribers for every financial year, for issuance of NCDs with a maximum subscription of less than ₹1 crore, and such subscription shall be fully secured;\n(4) There shall be no limit on the number of subscribers in respect of issuances with a minimum subscription of ₹1 crore and above; the option to create security in favour of subscribers shall be with the issuers. Such unsecured debentures shall not be treated as public deposits as defined in\nReserve Bank of India (Non-Banking Financial Companies - Acceptance of Public Deposits) Directions, 2025\n.\n(5) An NBFC shall issue debentures only for deployment of funds on its own balance sheet and not to facilitate resource requests of group entities/parent company/ associates.\n(6) An NBFC shall not extend loans against the security of its own debentures (issued either by way of private placement or public issue).\n12. Tax exempt bonds offered by NBFCs are exempted from the applicability of the circular.\n13. For NCDs of maturity upto one year, instructions contained in ‘\nMaster Direction – Reserve Bank of India (Commercial Paper and Non-Convertible Debentures of original or initial maturity upto one year) Directions, 2024’ dated January 03, 2024\n(as amended from time to time), issued by Financial Markets Regulation Department of the Reserve Bank, shall be applicable.\n1\nC.2 Directions on Private Placement of Equity Shares by NUCFDC (Umbrella Organisation for Primary Co-operative Banks)\n13A. National Urban Co-operative Finance and Development Corporation Limited (NUCFDC) may make offer or invitation to subscribe to its equity shares on a private placement basis to more than 200 persons in aggregate in a financial year, subject to the conditions specified herein below:\nNUCFDC shall have a Board approved policy for resource planning which,\ninter alia\n, covers the planning horizon and the periodicity of the private placement.\nOffer/invitation for the private placement of equity shares under these guidelines shall only be made to UCBs and National Co-operative Development Corporation (NCDC).\nThe offer document shall clearly state that UCBs must ensure compliance with all the applicable statutory requirements, as well as the extant instructions/directions issued by Reserve Bank when making an application for subscribing to the equity shares under the offer.\nNUCFDC shall not extend any loan or advance or any other kind of financial accommodation against the security of its own shares.\nProceeds of the share capital raised under these guidelines shall be used for the purposes consistent with the mandate of NUCFDC as approved by Reserve Bank.\nSubject to the provisions of these Directions, NUCFDC shall ensure compliance with all the applicable statutory and regulatory requirements with regard to the private placement of securities.\nNUCFDC shall submit a quarterly statement containing,\ninter alia\n, the amount of equity raised, the number and category of subscribers and the subscription amounts (during the quarter as well as cumulatively) to the Department of Regulation, Reserve Bank of India, Central Office within 15 days from the close of a quarter.\n13B. The Directions contained in paragraph 13A shall remain in force from the date of issue till March 31, 2029, unless modified or withdrawn earlier or extended further by the Reserve Bank.\nD. Technical Specifications for all participants of the Account Aggregator ecosystem\n14. The NBFC-Account Aggregator (NBFC-AA) consolidates financial information, as defined in\nReserve Bank of India (Non-Banking Financial Companies - Account Aggregator) Directions, 2025\nof a customer held with different financial entities, spread across financial sector regulators adopting different IT systems and interfaces. In order to ensure that such movement of data is secured, duly authorised, smooth and seamless, it has been decided to put in place a set of core technical specifications for the participants of the AA ecosystem. Reserve Bank Information Technology Private Limited (ReBIT), has framed these specifications and published the same on its website (\nwww.rebit.org.in\n).\n15. NBFCs acting either as Financial Information Providers or Financial Information Users are expected to adopt the technical specifications published by ReBIT, as updated from time to time.\nE. NBFCs not to be partners in partnership firms\n16. No NBFC shall contribute to the capital of a partnership firm or become a partner of such firm.\n17. Partnership firms shall also include Limited Liability Partnerships (LLPs).\n18. The aforesaid prohibition shall also be applicable in respect of Association of persons, these being similar in nature to partnership firms.\n19. An NBFC which had already contributed to the capital of a partnership firm /LLP / Association of persons or is a partner of a partnership firm / LLP or member of an Association of persons shall seek early retirement from the partnership firm / LLP / Association of persons.\nF. Ratings of financial products of NBFCs\n20. NBFCs with asset size of ₹100 crore and above shall furnish information about downgrading / upgrading of assigned rating of any financial product issued by them, within fifteen days of such a change in rating, to the Regional Office of the Reserve Bank under whose jurisdiction their registered office is functioning.\nG. Non-Reckoning of Fixed Deposits with banks as Financial Assets\n21. Investments in fixed deposits shall not be treated as financial assets and receipt of interest income on fixed deposits with banks shall not be treated as income from financial assets as these are not covered under the activities mentioned in the definition of “financial Institution” in section 45-I(c) of the RBI Act, 1934. Besides, bank deposits constitute near money and can be used only for temporary parking of idle funds, and/or in cases where the funds are parked in fixed deposits initially to fulfil the requirement of registration as NBFC, i.e., NOF of ₹10 crore, till commencement of NBFI business.\nH. Use of electronic payment system\n22. NBFCs shall take proactive steps for increasing the use of electronic payment systems, elimination of post-dated cheques and gradual phase-out of cheques in their day-to-day business transactions which would result in more cost-effective transactions and faster and accurate settlements.\nI. Migration of Post-Dated Cheques (PDCs) / Equated Monthly Instalment (EMI) Cheques to National Automated Clearing House (NACH)(Debit)\n23. Considering the protection available under section 25 of the Payment and Settlement Systems Act, 2007 which accords the same rights and remedies to the payee (beneficiary) against dishonour of electronic funds transfer instructions on grounds of insufficiency of funds as are available under section 138 of the Negotiable Instruments Act, 1881, there shall be no need for NBFCs to take additional cheques, if any, from customers in addition to NACH (Debit) mandates. Accordingly, NBFCs have been advised not to accept fresh/ additional PDCs or EMI cheques from their customers. Cheques complying with CTS-2010 standard formats alone shall be obtained in locations, where the facility of NACH is not available.\nJ. Disbursal of loan amount in cash\n24. NBFCs shall ensure compliance with the requirements under sections 269SS and 269T of the Income Tax Act, 1961, as amended from time to time.\nK. Customer Due Diligence for Transactions in Virtual Currencies (VC)\n25. It has come to our attention through media reports that regulated entities have cautioned their customers against dealing in virtual currencies by making a reference to the\nRBI circular DBR.No.BP.BC.104/08.13.102/2017-18 dated April 06, 2018\n. Such references to the above circular by regulated entities are not in order as this circular was set aside by the Hon'ble Supreme Court on March 04, 2020 in the matter of Writ Petition (Civil) No.528 of 2018 (Internet and Mobile Association of India v. Reserve Bank of India). As such, in view of the order of the Hon'ble Supreme Court, the circular is no longer valid from the date of the Supreme Court judgement, and therefore cannot be cited or quoted from.\n26. NBFCs, may, however, continue to carry out customer due diligence processes in line with regulations governing standards for Know Your Customer (KYC) prescribed in\nReserve Bank of India (Non-Banking Financial Companies – Know Your Customer) Directions, 2025\n, Anti-Money Laundering (AML), Combating of Financing of Terrorism (CFT) and obligations of regulated entities under Prevention of Money Laundering Act, (PMLA), 2002 in addition to ensuring compliance with relevant provisions under Foreign Exchange Management Act (FEMA) for overseas remittances.\nL. Rounding off of transactions to the Nearest Rupee\n27. All transactions of the NBFC, including payment of interest on deposits/ charging of interest on advances, shall be rounded off to the nearest rupee, i.e., fractions of 50 paise and above shall be rounded off to the next higher rupee and fractions of less than 50 paise shall be ignored. It shall be ensured that cheques/drafts issued by clients containing fractions of a rupee shall not be rejected by them.\nM. Provision of Safe Deposit Locker Facility by NBFCs\n28. Providing safe deposit locker facility is a fee-based service and shall not be reckoned as part of the financial business carried out by NBFCs. NBFCs offering safe deposit locker facility or intending to offer it, shall disclose to their customers that the activity is not regulated by the Reserve Bank.\nN. Attempt to defraud using fake bank guarantee - Modus Operandi\n29. Instances of fraud have been brought to the notice of the Reserve Bank wherein Bank Guarantees (BGs) purportedly issued by a couple of bank branches in favour of different entities were presented for confirmation by other commercial banks / individuals representing some beneficiary firms. The BGs were submitted along with Confirmation Advice / Advice of Acceptance. One of the beneficiaries was the reporting bank’s customer. The remaining beneficiaries and applicants were neither the customers of the bank nor were they known to the bank branch officials.\n30. A scrutiny of the said BG revealed that these bank guarantees were fake and the signatures of the bank officials appearing on the BG were forged. The bank branches purported to have issued the BGs also confirmed that they had not issued the same. Even the format of the BGs and their serial numbers did not match with that of the bank.\n31. NBFCs shall take notice of the above facts in order to exercise due caution while handling such cases.\nChapter-III Miscellaneous Instructions applicable to NBFCs in Middle Layer\nA. Licensing as Authorised Dealer- Category II\n32. In order to increase the accessibility and efficiency of forex services extended to the members of the public for their day-to-day non-trade current account transactions, non-deposit taking NBFC-ICC shall be eligible for Authorized Dealer- Category II (AD Cat II) license, subject to meeting the following conditions:\n(1) an NBFC offering such services shall have a ‘minimum investment grade rating’.\n(2) an NBFC offering such services shall put in place a board approved policy on:\n(i) managing the risks, including currency risk, if any, arising out of such activities; and\n(ii) handling customer grievances arising out of such activities.\n33. A monitoring mechanism, at least at monthly intervals, shall be put in place for such services.\n34. The eligible NBFC desirous of undertaking AD-Cat II activities shall approach the Reserve Bank, Foreign Exchange Department, Central Office, Mumbai for the AD-Cat II licence.\nChapter-IV Specific directions applicable to NBFC-Factors and NBFC-ICCs registered under the Factor Regulation Act, 2011\n35. The instructions contained in this Chapter for NBFC-Factors and NBFC-ICCs registered under the Fa